export const TWITTER_USERS = [
  "TheBullduck",
  "CryptoKemal",
  "ninjasquadnft",
  "ninjatraderstr",
  "ninjatoolsio",
  "umutak47shawty",
  "ninjanewsio",
  "nfdesignsio",
  "dotiryaki",
  "thunderbyFuel",
  "traderhamza",
  "nuhbatuhann",
  "GokhanGark",
  "cryptotrfacts",
  "barisbuyuktas",
  "kriptoegitimtr",
  "evox_dev",
  "evoxcapital",
  "hebys_io",
  "woodyapp",
  "leawoof",
  "CemalTheMM",
  "FaineraPro",
  "xbtirfan",
  "FelixTradeCap",
  "lord_of_crypto_",
  "AytuncYildizli",
  "AvalancheFDN",
  "avax",
  "profesorishere",
  "finderexglobal",
  "Wolfsschanze54",
  "kriptokrat5",
  "cryptoX_Wolfe",
  "KriptoChef",
  "yavuzsyildiz",
  "KelletorK",
  "ByECT",
  "zdcmadd",
  "bilalkalkan148",
  "richiereichrich",
  "findikvodka",
  "klintistvuud",
  "yavrugoril777",
  "abbasaydin",
  "Georgia_stokes0",
  "sodeeq64290",
  "xcoinmarketx",
  "eshothx",
  "yorgunS93968",
  "mehmet091224",
  "ThrowBombSailor",
  "4FuLL_Contact",
  "UurKerem9",
  "omer_oguz11930",
  "evansmathew455",
  "Aliko4935",
  "kostyaluthier",
  "gunkutbasat",
  "kalbimin_gogu",
  "strahdxxx",
  "skewChart",
  "sedat_peker",
  "XarriableFB",
  "zarriable",
  "alihfo",
  "Traderlands",
  "istanblsinema",
  "POPCATSOLANA",
  "traderkoray",
  "nnairob",
  "invest",
  "ranyi1115",
  "OrderlyNetwork",
  "DeFi_BabyPanda",
  "CoinfairGlobal",
  "genekmkz",
  "Azuki",
  "AnichessGame",
  "AzukiMalaysia",
  "Azukicks_IKZ",
  "FluffyAzuki",
  "AzukiAlphaBeans",
  "Kohiimaru",
  "boredice2018",
  "FrameBeans",
  "Kriptomessi",
  "serkanerden_",
  "SerkanErden_Eng",
  "WuBlockchain",
  "serifalienes",
  "OKX",
  "OkxTurkiye",
  "sabanci_sbs",
  "itu1773",
  "mutj07",
  "isil_kurnaz",
  "SantAnnaPisa",
  "ScuolaSantAnna",
  "LundUniversity",
  "RWallenbergInst",
  "SweInstitute",
  "BilkentUniv",
  "birikimdergisi",
  "0xgordongekko",
  "Leandoureth",
  "WinnerOkanBuruk",
  "GalatasaraySK",
  "mesut_aklay",
  "DreamsRust50227",
  "glnarelmaeyvav1",
  "0xZeynel",
  "v_on_vana",
  "MammothOverlord",
  "asclubnft",
  "ModularCards",
  "raf_mafia",
  "theloonies_nft",
  "TrustaLabs",
  "lavanetxyz",
  "KutudakiAdam_7",
  "TakaneNoHana_s",
  "LizzydotG",
  "CelikTugberk",
  "ubatuge07",
  "Firuzeln",
  "Airdropmons",
  "Sevki0x",
  "onlywithneo",
  "haloETH",
  "Bullx_io",
  "_s_l_a_t_e_",
  "Bybit_Official",
  "0xkovv",
  "Pelinakrsuuy",
  "Berrinmn",
  "Cerensereng",
  "Aleynavd",
  "Yelizfigan",
  "Keremannn",
  "movementlabsxyz",
  "Moca_Network",
  "mertuykuseven",
  "hoeheyAbii_",
  "komo032",
  "iamviktohtimmy",
  "Ahmett_Gultekin",
  "0xZeynel",
  "v_on_vana",
  "MammothOverlord",
  "asclubnft",
  "ModularCards",
  "raf_mafia",
  "theloonies_nft",
  "TrustaLabs",
  "lavanetxyz",
  "38KdotSOL",
  "Backpack",
  "MadLads",
  "0xMoonLander",
  "GonzoXBT",
  "PlayLegionGG",
  "LexRobsonGG",
  "kramaricnft",
  "mustemgul",
  "traderomercan",
  "lionfunded",
  "nftmufettisi",
  "WhaleWeb3_",
  "daosdotfun",
  "baosdotfun",
  "OrtegasCrypto",
  "btcoinmag",
  "nuhbatuhann",
  "GyuzaRidani",
  "AccessProtocol",
  "grvt_io",
  "CryptoKemal",
  "ninjasquadnft",
  "ninjatraderstr",
  "ninjatoolsio",
  "sezorock",
  "CryptoLego0311",
  "eaglesunionTR",
  "0x_tmdao",
  "barisbuyuktas",
  "kriptoegitimtr",
  "evox_dev",
  "evoxcapital",
  "hebys_io",
  "woodyapp",
  "huseyin1tekin",
  "alchdao",
  "jirasanofficial",
  "ordinaltools",
  "konohacrypt0",
  "Seymirel",
  "RWA_Inc_",
  "kesler",
  "tr4ck3rgg",
  "GAM3Sgg_",
  "SeedworldMeta",
  "Somnia_Network",
  "westkripto",
  "0xMrRed",
  "PicklesDAO",
  "0xRemiss",
  "ZkCampus",
  "ZkCampusTR",
  "infernotrenches",
  "Aptos",
  "Daosdotfun",
  "ustadsplinter34",
  "omerdemircrypto",
  "Foxilynn",
  "alisadeghian_",
  "Adem2336Arya",
  "guaclee_",
  "sadollahba",
  "msyafiq9398",
  "ljiljananedeljk",
  "Ericsaku3",
  "OWHY6oNippRveMs",
  "djetouandomini2",
  "Nh_Aldossary",
  "RafaMor45229623",
  "84502eec3ff64d2",
  "bill_onMM",
  "CryptoN64168818",
  "33NG1",
  "hiteshhitu403",
  "theKriptolik",
  "hyenasweb3",
  "LupoABS",
  "Abstractchain",
  "playduper",
  "AbstractChain",
  "AbstraUniverse",
  "CoinElevate",
  "kriptobi",
  "Yennii56",
  "aixbt_agent",
  "LancaTR",
  "concero_io",
  "chainlink",
  "soon_svm",
  "PvPGameHub",
  "Amino_Chain",
  "0xlaplaced",
  "shannholmberg",
  "lunarstrategy",
  "icphub_PT",
  "icp_france",
  "cryptoaicon",
  "vybit_app",
  "edenwagmi",
  "Monadians_xyz",
  "seizzi",
  "grinnznft",
  "ThePatrunos",
  "epiknft",
  "Mindblowon_io",
  "lickpalik",
  "mycelium_io",
  "3BerasCapital_",
  "daosdotworld",
  "Bu_Zhu_",
  "ByleDavies",
  "3BCbintern",
  "quillsadventure",
  "AimonicaBrands",
  "gianinaskarlett",
  "gigiskarlett",
  "Alecness1",
  "MultiChainInc",
  "BiptapOfficial",
  "Lingocoins",
  "theArenaApp",
  "tokenomicsguy",
  "tarindd",
  "monad_xyz",
  "lunarfoxdao",
  "kylesamAIni_",
  "multicain",
  "cleopetrafun",
  "chogstarrr",
  "IamAqsaShaikh",
  "Ouroboros_xyz",
  "surgence_io",
  "gomblegames",
  "xocietyofficial",
  "overtake_world",
  "the77bit",
  "MelancholyJimmy",
  "MulticAIn",
  "kev4evaa",
  "Konn3cted",
  "Raoulgmi",
  "Madlads",
  "The_Barrows",
  "0xfrigg",
  "sporedotfun",
  "SayEchooo",
  "Citadailhedge",
  "griffaindotcom",
  "memeillionaire",
  "dao_aisu",
  "ColumbAIagent",
  "aisuagent",
  "SynthGirlFund",
  "spikynads",
  "defiremora",
  "PBrasilNFT",
  "RaveniumNFT",
  "EclipSensei",
  "TONStationLabs",
  "TobbyKitty",
  "DoganEth",
  "cyberFund_",
  "doganeth_en",
  "lyteraio",
  "getclave",
  "AytuncYildizli",
  "AvalancheFDN",
  "avax",
  "yavuzsyildiz",
  "0xSmartContract",
  "TanselKayaTR",
  "HeathleyETH",
  "Hoodies_CT",
  "HoodRunio",
  "layer3xyz",
  "AbstractChain",
  "0xRemiss",
  "ZkCampus",
  "ZkCampusTR",
  "infernotrenches",
  "Aptos",
  "Moca_Network",
  "Daosdotfun",
  "0xStrat",
  "barisbuyuktas",
  "kriptoegitimtr",
  "evox_dev",
  "evoxcapital",
  "hebys_io",
  "woodyapp",
  "OrtegasCrypto",
  "daosdotfun",
  "tervelix",
  "dejondefi",
  "OrientusPrime",
  "ustadsplinter34",
  "CryptoChille",
  "LibraryDefi",
  "TOGG2022",
  "aselsan",
  "METU_ODTU",
  "yasinaktimur",
  "vrnouns",
  "cryptoX_Wolfe",
  "CryptoLego0311",
  "eaglesunionTR",
  "BosBosbigbos",
  "2yilmaz2",
  "Sarsotio8K_",
  "Arda__JK",
  "muratkerem111",
  "_Gel_Hele_Gel_",
  "mesutkaratas111",
  "Alphapars",
  "FluswapExchange",
  "LumozOrg",
  "MantaNetwork",
  "puffpaw_xyz",
  "AstraeaDAO",
  "1MinuteWeb3",
  "ocean9ravity",
  "spacebotu",
  "Mpairdbap",
  "GokayKayki",
  "VEDAT_GMS",
  "peaq",
  "aipeaq",
  "TendeauhSAQ",
  "PloujurgriQy65",
  "mrt_uls",
  "ates0145",
  "_73kereem",
  "9baldurix",
  "incetolgaa",
  "riseinweb3",
  "BurakBodurolu1",
  "alperakyol45",
  "orkutkaksa",
  "0xGamerCrypto",
  "CryptoxNimbus",
  "MadLads",
  "SenolVatansever",
  "kriptoderorg",
  "powerexcrypto",
  "Watch2EarnMedia",
  "benguturktv",
  "DijitalBiz",
  "Providence_Tr",
  "PlayProvidence",
  "1DynastyStudios",
  "mustafakahya388",
  "srncbycom",
  "0xliseliemre",
  "atelierarasta",
  "temettuapp",
  "maslaklabs",
  "ITUblockchain",
  "fuelnetworkTR",
  "langeriuseth",
  "HuntersofWeb3",
  "bora_ozenbirkan",
  "velanorETH",
  "eoracle_network",
  "efrogs_on_linea",
  "Yooldo_Games",
  "LiveArtX",
  "vkorkmaz10",
  "Altcointurk",
  "KriptoCuma",
  "AltcointurkBase",
  "Besiktas",
  "NeedB_",
  "cemercan84",
  "BesiktasEnglish",
  "PABL0_1989",
  "2LoudNetwork",
  "CryptooSeneR",
  "Cryptoloss1",
  "BringMeCoins",
  "UgurcnU",
  "hoodrunio",
  "Rhuax",
  "SerkanBALBAL",
  "TheturkNFT",
  "Innovion1",
  "avniguven_",
  "avalabsofficial",
  "AlpaslanGence",
  "atabrocky",
  "ifmmediatv",
  "blockhoood",
  "CoinDesk",
  "askincimen",
  "kavvambirbey",
  "ulquiomaru",
  "akob1a",
  "danimonke",
  "klriptoris",
  "TanselArbay",
  "Murat12626",
  "CryptoAIchemist",
  "angelofmoonb",
  "itsefekucuk",
  "bjk_ahmettt",
  "yaman_dev",
  "Coinbed1",
  "Yozcifci",
  "yigitax",
  "DoyleHarris73",
  "CarefulMassacr",
  "Kaplantgra",
  "0xMillanito",
  "Ryznva",
  "BensonRubby",
  "iLLuminateAu",
  "spaace_io",
  "my_friend_jimi",
  "rakib_md28659",
  "libbegum",
  "elonwens",
  "professorabhay",
  "ChromiumDev",
  "keizerHQ",
  "techbastic",
  "Jamopyper",
  "_TheProfitHub",
  "Zzvonarka",
  "TsheringDo36435",
  "9oo8k",
  "TanDay84840445",
  "xiaowuDD666",
  "Oreocream_milk",
  "meepoing",
  "Corprend",
  "CongratsFNF",
  "sight_zero",
  "threaded_finger",
  "CryptoNight420",
  "btt_cz",
  "Hade_deji",
  "AlexARGaming",
  "AvaxDAO_",
  "Soulbound_GG",
  "pixels_online",
  "AxieInfinity",
  "PeterAdetona",
  "_Farm_Kang_",
  "LangaTsher97106",
  "doresmarlindo1",
  "Arena_mindset",
  "fadliarr_",
  "keziazoidao3",
  "syifa277650",
  "EmaFavretto",
  "banghaji0543",
  "0DandG",
  "mollik39256",
  "tokes_jay",
  "tokes",
  "Amrita128561372",
  "WangchukNo35713",
  "iamaboffin",
  "HyperspaceAvax",
  "AnoopWeb3",
  "VaynerMedia",
  "SolNFTs",
  "MagicEden",
  "indiemonkes",
  "NiKoLa_TeSlA_v2",
  "Nero_Investing",
  "rektbuildr",
  "avaxto",
  "REKTBuildr",
  "LilliVibe",
  "WEB3Eliza",
  "tonstonks",
  "Yescoin_Fam",
  "WizArt_Studios",
  "sunnymaanz",
  "DeGodsNFT",
  "mandalaangel",
  "RefMonster",
  "TheArenaApp",
  "Sword_Base",
  "KimboAvax",
  "avax",
  "KimbrosNFT",
  "nochillavax",
  "CoqInuAvax",
  "WojakSatoshi",
  "thisisomgart",
  "Crypto_Ascend",
  "RockieRockie_",
  "The_Daily_Alpha",
  "lekejnr__",
  "lonelyly_cat",
  "JMMcBreairty",
  "memegoai",
  "bubits_",
  "GainerStalder",
  "duniterum",
  "nostoryboss",
  "0xThaDream",
  "web3_nk",
  "melobirdx3",
  "switchboardxyz",
  "skrumpeys",
  "JTWiseGuy",
  "LSKD",
  "STICKavax",
  "tokenterminal",
  "andrebeganski",
  "decryptmedia",
  "routescan_io",
  "ihoramster",
  "Azuki",
  "UniswapFND",
  "AcrossProtocol",
  "UMAprotocol",
  "thisisomgart",
  "hildobby_",
  "dragonfly_xyz",
  "indexed_pod",
  "CryptoRubic",
  "DEXToolsApp",
  "0xadon",
  "kbwofficial",
  "zaryab_eth",
  "pushprotocol",
  "DecipherClub",
  "blockscoutcom",
  "kewlswap",
  "Optimism",
  "OPLabsPBC",
  "OptimismGov",
  "FreddieRaynolds",
  "ODIGco",
  "Uniswap",
  "TrustlessState",
  "Banklesshq",
  "gitcoin",
  "GrantsStack",
  "GitcoinPassport",
  "AlloProtocol",
  "wenaltcoin",
  "haydenzadams",
  "0ga_Tatsumi",
  "alltayfurkan",
  "BenDiFrancesco",
  "ScopeLift",
  "UmbraCash",
  "pillibebek77",
  "ki_young_ju",
  "cryptoquant_com",
  "thenotoriousegc",
  "jorgeschnura",
  "VerisLabs",
  "TuringCapital_",
  "MovistarKOI",
  "sourcedtech",
  "tyba",
  "deacix",
  "1inch",
  "natebirdman",
  "tamagui_js",
  "one__js",
  "unquale",
  "austingriffith",
  "BenaAlislm",
  "MrFanToken",
  "IntractAmbassador",
  "DoganEth",
  "cyberFund_",
  "doganeth_en",
  "lyteraio",
  "getclave",
  "0xismailemin",
  "thepharus",
  "arbitrum",
  "itublockchain",
  "EthyleneStudio",
  "StarkNetTurkiye",
  "luckycoin2034",
  "AnggerReva34680",
  "Salii64",
  "Dulabai21",
  "Shavai30",
  "whydulls",
  "Boss3463",
  "muhammad_b18055",
  "durri53",
  "Baikoi53",
  "PutraMarce38107",
  "AirdropE74",
  "maulanaidr66053",
  "Batpar01",
  "amin656111",
  "Johirul738",
  "Jullya472",
  "m_faajr35282",
  "Zerahhh24",
  "AmbadulM",
  "GorJamaii",
  "Paich0",
  "matkilat1272189",
  "AlaynaBrig73",
  "Bhoneraa",
  "KendreGureh",
  "Bijoynogar",
  "BalleCasandra",
  "Kenoo134",
  "ox_gama",
  "Sumiya476",
  "An4kPasiee",
  "KelleyMila74769",
  "Barijabo22",
  "Qwerty1566651",
  "Onik166",
  "MirJafoor",
  "Karun594",
  "MdJewel887",
  "Ahura22710",
  "ShadiyaTor",
  "Potato454879",
  "plepeleloo",
  "NurLaila246112",
  "devinawalsh",
  "UniswapFnd",
  "Mclader",
  "uniswap",
  "NuwanShilpa",
  "_junhoyeo",
  "wemintcash",
  "AJAYx2",
  "G7_DAO",
  "StellarArchite1",
  "ConCac40936505",
  "cvex_xyz",
  "FUKDUKonTON",
  "CFBcaveman",
  "Aimbotting",
  "RobausHalle",
  "CryptoJimiX",
  "playbigtime",
  "OpenLoot",
  "hxh_bro",
  "w4Rd3n",
  "theonewhomogs_",
  "staderlabs",
  "PalmNft",
  "Sheldon_Sniper",
  "FairyproofT",
  "YetiSwap",
  "avalancheavax",
  "nansenportfolio",
  "Karasakalz",
  "uniswapgrants",
  "swetherofficial",
  "treum_io",
  "TensorDetective",
  "DujunX",
  "DealeanCapital",
  "PancakeSwap",
  "mooniswap",
  "Gal__Eldar",
  "MetaMask",
  "nerve_network",
  "HanafiMustafid",
  "Malocro96",
  "TsunamiVibes_",
  "0xLemuel",
  "p1studio_xyz",
  "zealy_io",
  "starknet",
  "civickey",
  "amplifi_fi",
  "PolygonLisbon",
  "88_Flin_88",
  "yasonya_",
  "Hashidu55",
  "AvatarFSH",
  "kodak",
  "Canon",
  "PPavlus24854",
  "Anton1oPlmr",
  "MastBahar15588",
  "dergunov_egor",
  "AiAigallery",
  "Pengemisjalan10",
  "zonly_lion",
  "JackNel42737626",
  "moj3miner",
  "POPAY____",
  "WiZzTracker",
  "unar443535",
  "Saj1340918",
  "PRATIKPAWA71541",
  "lay2000lbs",
  "pooltogether_",
  "pleasrdao",
  "pplpleasr1",
  "SteveyTrommm",
  "opensea",
  "dharma_hq",
  "summit",
  "dcwj",
  "blackbird_xyz",
  "helium",
  "ppyapali",
  "Uber",
  "SonderStays",
  "Zynga",
  "ack_129",
  "vig_xyz",
  "Drift",
  "Kensho",
  "kayrgeorge",
  "stanford",
  "AustinAdams10",
  "whetstonedotcc",
  "variantfund",
  "agray1205",
  "sharedotxyz",
  "Scott_eth",
  "geniexyz",
  "UniswapLabsVC",
  "xin__wan",
  "stevibiel",
  "boysclubcrypto",
  "0xSisyphus",
  "Gelly_Acosta",
  "lclamont415",
  "hensha256",
  "OpenZeppelin",
  "FedorovMykhailo",
  "stephaniemehta",
  "justindomingue",
  "superstatefunds",
  "EthereumDenver",
  "SporkDAO",
  "BufficornV",
  "CUNY",
  "djnf",
  "evdawgcrypto",
  "0definitely0",
  "SarsonFunds",
  "d1ventures",
  "sirada_l",
  "gate_ventures",
  "avaxdao_",
  "Cambridge_Uni",
  "LifeAtPurdue",
  "MisakiBNB",
  "SmolMobster",
  "nautsmeme",
  "ThePitGame",
  "Crouserrr",
  "EYEKONNFT",
  "rollbit",
  "the_viiibe",
  "lfj_gg",
  "monad_xyz",
  "replyheroxyz",
  "dural_sh",
  "666Nothingman",
  "TECHimproving",
  "heymaximillian",
  "nodekitorg",
  "columbia",
  "NYUniversity",
  "frucksBTC",
  "Kelso_MKK",
  "goldsmols",
  "Florida__Man__",
  "amiavax",
  "frankdegods",
  "degodsnft",
  "probablynothing",
  "HerroCrypto",
  "tisbutascratch3",
  "elliotherium",
  "cookoutclubxyz",
  "ownthedoge",
  "Credzilla",
  "KazeCreations",
  "Mr_GLCCK",
  "PaulinaRez_",
  "necessarygrowth",
  "eclipse_L1",
  "PyreSwap",
  "CryptoOrlandoFL",
  "BSturisky",
  "Starknetfndn",
  "Delphi_Digital",
  "DrSausagesPHD",
  "DJM09068876",
  "Moom_Town",
  "HugeHenSL",
  "SeedworldMeta",
  "TheMiraiLabs",
  "creators_nexus",
  "SouthernLabs",
  "FreeTed25",
  "RayFink0231",
  "OleLong_Johnson",
  "DwccHub",
  "haloETH",
  "Bullx_io",
  "_s_l_a_t_e_",
  "Bybit_Official",
  "2peacks",
  "v_slayers",
  "Ghamgha",
  "Wallroadman",
  "innerwondersapp",
  "sureplug_",
  "CobraRosso81",
  "uwucrewnft",
  "KadirSangaa",
  "afreecanism",
  "aitach_kenya",
  "1TrueAltitude",
  "MetaMaddHatter",
  "dok_stores",
  "lxcas_eth",
  "thisisomgart",
  "Marilla_04",
  "Hassanmoha37082",
  "ShubhCryptoTon",
  "seco060626",
  "barthmans",
  "KB7613",
  "theresa52689",
  "smith_paulrou",
  "CrawfordkrClar",
  "Umamahesh8899",
  "mary_tayloDim",
  "WilliamSulsb",
  "Tylernealcr",
  "indira148662",
  "AngelaBoydnatoy",
  "NicoleGrifsh",
  "Kelliegsa",
  "Fletch832",
  "Katiehaynescou",
  "Arena_mindset",
  "Perushki",
  "scrapper302",
  "Amit_fitandfast",
  "MrSandeepReddy",
  "KoinoYo35772686",
  "lantik_ir",
  "LongDitMap",
  "PepeAptos",
  "ElCryptoKostel2",
  "dgc5813",
  "Zulfikar343434",
  "Grizlrr",
  "Crypto_Lover_66",
  "jagseerSin48743",
  "curry_caro32351",
  "1966302432888x",
  "mdarafat175",
  "RealVandah",
  "Richardson80818",
  "jamil_emrys",
  "arfkzltp",
  "PercyVerence0",
  "_WOOFi",
  "HTX_Global",
  "Ahnor_Block",
  "AvalancheFDN",
  "AvaLabs",
  "Avax",
  "InviteToMystery",
  "mysteryfdn",
  "canadianplayer",
  "chikn_nft",
  "joepegsnft",
  "LFJ_gg",
  "bitgetglobal",
  "LaLigaEN",
  "BitgetSupport",
  "cryptojourneyrs",
  "LFGNOW1",
  "Matt_Furie",
  "CultureOnAvax",
  "avax",
  "TheCryptoLark",
  "WealthMastery_",
  "BenqiFinance",
  "pixelverse_xyz",
  "coqbook",
  "Landslide_Labs",
  "Coqinutube",
  "AltcoinDailyio",
  "stvngts",
  "GoGoPool_",
  "HD420O",
  "0x_dano",
  "coq_media",
  "vaneck_us",
  "CryptosR_Us",
  "AlphaFirst_",
  "InfluFightClub",
  "SuzakuNetwork",
  "gate_io",
  "el33th4xor",
  "avalabs",
  "Cornell",
  "initc3org",
  "coqnet_io",
  "coingecko",
  "GeckoTerminal",
  "delaunch",
  "ai9000_delaunch",
  "NFTdavie",
  "SlingshotCrypto",
  "jooce_coin",
  "otivnod",
  "BeamFDN",
  "luigidemeo",
  "Citi",
  "conorfkenny",
  "AvaxNFTs",
  "AvaxDAO_",
  "AvaxMachina",
  "SherbokH",
  "BinanceFutures",
  "digitalartchick",
  "cz_binance",
  "binance",
  "COQ_AI",
  "RobinhoodApp",
  "coinbase",
  "CoinbaseSupport",
  "BinanceHelpDesk",
  "coinspotau",
  "OXFUNHQ",
  "0xNFTreasure",
  "LunarCrush",
  "CoqUniversity",
  "khlod__768",
  "Baranmslm13",
  "duke_rick1",
  "youcallmeflexy",
  "stein9658",
  "tierra_io",
  "Yozcifci",
  "cryptoBobX1",
  "Sari33_33",
  "cagyjan1",
  "KAI1586",
  "Enzi166",
  "aIoudcIoud",
  "SirWizziWizz",
  "angthesenpai",
  "_DeFi_avax",
  "DeFi",
  "De_FiSecurity",
  "atabrocky",
  "ifmmediatv",
  "ay00ant",
  "ulquiomaru",
  "Hoopoe_X",
  "ersanyakit",
  "Sirgraywolff",
  "0xEtherpulseE",
  "DanQB13",
  "StepFog",
  "ThruX_t",
  "allstarsng",
  "aryzeofficial",
  "DobiVanKenobi",
  "qwxdswqrib",
  "princesetia81",
  "flows_global",
  "ArgoAvax",
  "AvaxDAO_",
  "bulentbalci903",
  "Magnanimous64",
  "snapsnocaps",
  "ChatOnChain",
  "AVAXolotls",
  "avax",
  "LadyCryptoCalls",
  "TheCryptoKidsX",
  "ShielaAnnme",
  "AaronCryptoUK",
  "21Arifbaran",
  "CryptoPilotu",
  "SteefBreed",
  "raid_cc",
  "Assimilate_cc",
  "base",
  "MakerNewsletter",
  "garajotomotiv",
  "MayraRuiz723068",
  "MerveilM21502",
  "MayraN16956",
  "GopalPandi2001",
  "kaimaela",
  "Bravehe51389195",
  "ConorNo63530662",
  "Asceticism_1",
  "jasonbaudendist",
  "ForbesWeb3",
  "cryptowhaleride",
  "statushi1",
  "HangLu20",
  "brahim78486528",
  "salahtako",
  "AnohnehX",
  "TimBurg04260645",
  "AuwalMahmud2025",
  "biggsnake82",
  "DTrader26",
  "lil_Degens",
  "BlizzardFund",
  "S1Y4HS4NC4KS",
  "Monad_xyz",
  "DoctrineLabs",
  "BinanceTR",
  "BinanceTRDestek",
  "Avalanche_Space",
  "ParibuCom",
  "Binance_Turkish",
  "BinanceHelpDesk",
  "uzmancoin",
  "CryptoXMad",
  "Avalaunch_TR",
  "TheSandboxGame",
  "MetaHoundGame",
  "RocoFinance",
  "ITUblockchain",
  "GenesisBchain",
  "ITUBlockchainen",
  "coinmuhendisim",
  "habermuhendisim",
  "borsamuhendisim",
  "ethereum",
  "solana",
  "SolanaFndn",
  "cz_binance",
  "binance",
  "goodyboodygame",
  "deliqfinance",
  "akitavax",
  "heroesofnft",
  "Avax_News",
  "avaxholic",
  "GameFiEdge",
  "CSpaceship_",
  "top7ico",
  "gate_io",
  "CryptoDiffer",
  "YetiSwap",
  "avalancheavax",
  "Avalanche_vn",
  "WeekInAvalanche",
  "AvalancheID",
  "avalabs",
  "Islander_io",
  "RiseOnlineWorld",
  "mutlakbutlan4",
  "kemalc16",
  "LordPatatesTv",
  "_clb61",
  "safailkaya",
  "AyseGrdl",
  "emiryuksel1O",
  "OgurBas1989",
  "BerkayKasappp",
  "AHMETEMNER1",
  "LazHayalet",
  "mericerdogann",
  "SjwTemel",
  "selimcavus007",
  "AmaruqAaquaq",
  "WMehmetErcan",
  "MelihOztur94003",
  "velfarre_trance",
  "Mooncoinss",
  "biliyormuyduk1",
  "94vjjz9qt8",
  "egeecakiroglu"
]

export const EMOJIS = [
    "😊", "🚀", "🔥", "💎", "💰", "⚡", "🌍", "🎉", "🌟", "💡", "✨", "💥", 
    "🌈", "💯", "👑", "🎯", "🚨", "🤑", "👀", "🥇", "💬", "🎵", "⚔️", "🍀", 
    "📈", "💪", "🏆", "💥", "🌠", "🌙", "🦄", "🥂", "🎁", "🔑", "🍾", "🔮", 
    "🥳", "🎬", "🔔", "👑", "🌸", "🔥", "🍀", "💃", "🏅", "🏖️", "🏄‍♂️", "🧠", 
    "💭", "🤩", "🎮", "🦸‍♀️", "🦸‍♂️", "🕹️", "🍕", "🍔", "🍩", "🌮", "🍿"
  ];

 export const TWEETS = [
    "Help me become a millionaire! Join #MillionarMap and get started today!",
    "Ready to change your life? Sign up with my referral on #MillionarMap!",
    "Want to be rich? #MillionarMap is your way to go. Join me now!",
    "Unlock your millionaire potential with #MillionarMap. Let’s do this!",
    "Join #MillionarMap and let’s make millions together!",
    "This is your chance to become a millionaire! Join #MillionarMap with my referral.",
    "Millionaire life starts here! Join #MillionarMap now!",
    "Make your dreams a reality with #MillionarMap. Let’s get rich!",
    "Want to change your future? #MillionarMap is your key to success!",
    "Let’s start your millionaire journey together on #MillionarMap!",
    "Don’t wait to be rich! Join #MillionarMap and start today!",
    "#MillionarMap is the opportunity you’ve been waiting for. Join now!",
    "Your millionaire future is just one click away. Sign up on #MillionarMap!",
    "It’s time to level up! Start your millionaire journey with #MillionarMap!",
    "Want to be a millionaire? Sign up for #MillionarMap with my referral now!",
    "Join #MillionarMap and take control of your financial future!",
    "Become a millionaire with #MillionarMap. Get started today!",
    "Your path to wealth starts here. Join #MillionarMap with my link!",
    "Ready to get rich? #MillionarMap is the key. Join me!",
    "Start your millionaire journey today with #MillionarMap. Let’s go!",
    "The road to riches is waiting for you on #MillionarMap. Sign up now!",
    "With #MillionarMap, your wealth-building journey begins today!",
    "Want financial freedom? Let’s get started on #MillionarMap!",
    "Don’t just dream about being a millionaire. Join #MillionarMap and make it happen!",
    "Sign up for #MillionarMap and take the first step towards becoming a millionaire!",
    "This is your chance to change your life. Join #MillionarMap today!",
    "Become a millionaire with #MillionarMap! Sign up now!",
    "Start your millionaire story on #MillionarMap with me today!",
    "Change your life with #MillionarMap. Sign up and get started!",
    "Don’t miss your chance to be a millionaire. Join #MillionarMap!",
    "The journey to wealth starts with #MillionarMap. Sign up today!",
    "#MillionarMap is your chance to make millions. Join now!",
    "Ready to be a millionaire? #MillionarMap is the way. Let’s get started!",
    "Your financial freedom starts now! Join #MillionarMap!",
    "Sign up for #MillionarMap and unlock the millionaire in you!",
    "Time to become a millionaire! Join #MillionarMap today!",
    "Wealth is waiting for you on #MillionarMap. Sign up now!",
    "Take the first step to riches with #MillionarMap!",
    "#MillionarMap is your key to financial success. Join today!",
    "Want to be rich? Let’s start with #MillionarMap!",
    "Millionaire dreams? #MillionarMap is the way to make them real!",
    "Join #MillionarMap now and start working towards your millionaire future!",
    "Ready to get rich? Start on #MillionarMap today!",
    "The million-dollar opportunity is here. Join #MillionarMap now!",
    "Start building your wealth with #MillionarMap today!",
    "Join me on #MillionarMap and let’s make millions together!",
    "Wealth is within reach with #MillionarMap. Sign up now!",
    "Your millionaire future starts here with #MillionarMap!",
    "Don’t miss out on becoming a millionaire. Join #MillionarMap today!",
    "#MillionarMap is your opportunity to change your life. Sign up now!",
    "The path to wealth starts with #MillionarMap. Join now and get started!",
    "Start your millionaire journey with me! #MillionarMap is the way!",
    "Unlock your potential and join #MillionarMap today. Let’s make millions!",
    "Ready to be rich? The journey begins with #MillionarMap. Join me now!",
    "Take control of your financial future with #MillionarMap. Join now!",
    "A million dollars could be yours. Start on #MillionarMap today!",
    "The secret to becoming a millionaire is right here. #MillionarMap!",
    "It’s time to stop dreaming and start doing. Join #MillionarMap now!",
    "Join me on #MillionarMap and let’s reach new heights together!",
    "Wealth is just a click away. Sign up for #MillionarMap today!",
    "Your millionaire future starts now. Join #MillionarMap and take action!",
    "Start building wealth today with #MillionarMap. Let’s do this!",
    "This is the chance you’ve been waiting for. Join #MillionarMap and become a millionaire!",
    "Let’s make your millionaire dreams a reality with #MillionarMap!",
    "Join #MillionarMap and start earning your way to the top!",
    "Your millionaire future is just one step away. Take it with #MillionarMap!",
    "Millionaire status is within reach. Start on #MillionarMap today!",
    "Unlock financial freedom today. Join #MillionarMap now!",
    "The million-dollar opportunity is here. Don’t miss out on #MillionarMap!",
    "Becoming a millionaire has never been easier. Join #MillionarMap!",
    "Let’s turn your dreams into reality. Join #MillionarMap now!",
    "Want financial success? Start with #MillionarMap today!",
    "Start your millionaire journey today with the power of #MillionarMap!",
    "Join #MillionarMap and start making money today!",
    "This is your chance to become a millionaire. Join #MillionarMap now!",
    "The road to riches begins now. Join #MillionarMap and take the first step!",
    "Create your millionaire future with #MillionarMap. Join now!",
    "Don’t let this opportunity slip away. Join #MillionarMap today!",
    "Start building your wealth with #MillionarMap. Let’s get rich!",
    "Millionaire dreams can come true. Join #MillionarMap now!",
    "Take charge of your financial destiny. Join #MillionarMap today!",
    "Your path to a million starts here. Sign up for #MillionarMap!",
    "The journey to a million dollars starts with #MillionarMap. Join today!",
    "Ready to change your life? Join #MillionarMap and get started now!",
    "Let’s make millions together. Join #MillionarMap today!",
    "The millionaire opportunity you’ve been waiting for is here. Join #MillionarMap!",
    "Take the first step towards wealth. Join #MillionarMap today!",
    "Start your millionaire journey now with #MillionarMap!",
    "Your millionaire future is closer than you think. Join #MillionarMap!",
    "Ready to invest in your future? Join #MillionarMap today and start earning!",
    "Join #MillionarMap and take control of your financial destiny!",
    "Millionaire success starts with one decision. Join #MillionarMap now!",
    "This is your moment. Join #MillionarMap and get started on your wealth journey!",
    "The chance to be a millionaire is here. Don’t miss it. Join #MillionarMap!",
    "Start building the life of your dreams. Join #MillionarMap today!",
    "Let’s make a million together. Join #MillionarMap now!",
    "Ready to unlock your wealth with blockchain technology? Join #MillionarMap today!",
    "The future of finance is blockchain. Start your millionaire journey with #MillionarMap!",
    "Blockchain is the key to financial freedom. Join #MillionarMap now!",
    "Join the blockchain revolution and become a millionaire with #MillionarMap!",
    "Ready to earn with blockchain? Start today on #MillionarMap!",
    "Blockchain can make you a millionaire. Let’s start with #MillionarMap!",
    "Your million-dollar opportunity starts with blockchain on #MillionarMap!",
    "Blockchain + #MillionarMap = Your path to wealth! Join now!",
    "Want to invest in the future? Blockchain is the answer. Start with #MillionarMap!",
    "Change your financial future with blockchain. Join #MillionarMap today!",
    "Blockchain technology is the future. Join #MillionarMap and get rich!",
    "The best way to build wealth? Blockchain. Join #MillionarMap today!",
    "Blockchain is the future of money. Get ahead with #MillionarMap!",
    "Become a blockchain millionaire with #MillionarMap. Join today!",
    "Blockchain is the key to unlocking millions. Start with #MillionarMap!",
    "Ready to build wealth through blockchain? Start on #MillionarMap now!",
    "Blockchain is changing everything. Join #MillionarMap and be part of it!",
    "Unlock your financial success with blockchain on #MillionarMap!",
    "The power of blockchain is yours to harness on #MillionarMap. Join now!",
    "Wealth is built on blockchain technology. Join #MillionarMap to get started!",
    "Blockchain + #MillionarMap = Your ticket to financial success!",
    "Join the blockchain boom and start building your fortune with #MillionarMap!",
    "Start making money with blockchain. Join #MillionarMap today!",
    "Blockchain makes millionaire dreams come true. Start with #MillionarMap!",
    "Ready to use blockchain to get rich? Join #MillionarMap today!",
    "The blockchain era is here. Join #MillionarMap and build your fortune!",
    "Blockchain is the foundation for future wealth. Start with #MillionarMap now!",
    "Your path to millions is powered by blockchain. Join #MillionarMap!",
    "Blockchain technology can make you rich. Join #MillionarMap today!",
    "Take control of your financial destiny with blockchain. Join #MillionarMap!",
    "The future is blockchain. Get started on your millionaire journey with #MillionarMap!",
    "Blockchain is changing how we make money. Join #MillionarMap today!",
    "Start earning through blockchain. Join #MillionarMap now!",
    "Blockchain is revolutionizing finance. Join #MillionarMap and get rich!",
    "Your blockchain-powered future starts now. Join #MillionarMap!",
    "Blockchain and #MillionarMap are the keys to your financial success!",
    "The wealth-building power of blockchain is here. Join #MillionarMap today!",
    "Don’t miss out on blockchain wealth. Join #MillionarMap now!",
    "Ready to make money with blockchain? Start on #MillionarMap today!",
    "Blockchain is your gateway to a millionaire future. Join #MillionarMap!",
    "Get rich with blockchain and #MillionarMap. Join today!",
    "Blockchain wealth starts here. Join #MillionarMap and get started!",
    "The blockchain future is yours. Join #MillionarMap and make millions!",
    "Blockchain is the new gold. Start mining your wealth with #MillionarMap!",
    "Don’t just watch blockchain’s rise, be a part of it. Join #MillionarMap!",
    "Your path to blockchain riches starts today. Join #MillionarMap!",
    "Blockchain is the future of wealth. Get started now with #MillionarMap!",
    "Start your blockchain journey and become a millionaire with #MillionarMap!",
    "Join the #Chiliz movement and start your millionaire journey today with #MillionarMap!",
  "Ready to get rich with blockchain and #Chiliz? Join #MillionarMap now!",
  "#Chiliz is the future of sports and blockchain. Get in on the action with #MillionarMap!",
  "Unlock your wealth with #Chiliz and #MillionarMap. Join now!",
  "Become a millionaire with #Chiliz and blockchain technology. Start with #MillionarMap!",
  "Take control of your financial future with #Chiliz and #MillionarMap!",
  "The combination of #Chiliz and blockchain is your ticket to wealth. Join #MillionarMap!",
  "Join #MillionarMap today and use the power of #Chiliz to make millions!",
  "Ready to change your life with #Chiliz and blockchain? Get started on #MillionarMap!",
  "The #Chiliz blockchain is your opportunity to get rich. Join #MillionarMap now!",
  "Start your journey to wealth with #Chiliz and blockchain. Join #MillionarMap!",
  "#Chiliz and #MillionarMap are the perfect pair to make your dreams come true. Join now!",
  "Use the power of #Chiliz and #MillionarMap to unlock financial success!",
  "The future is #Chiliz. Join #MillionarMap and build your wealth today!",
  "Join #MillionarMap and let #Chiliz help you create your millionaire future!",
  "Don’t miss out on the #Chiliz revolution. Start your millionaire journey with #MillionarMap!",
  "Ready to earn with #Chiliz and blockchain? Join #MillionarMap and get started today!",
  "Your millionaire future is powered by #Chiliz and blockchain. Join #MillionarMap now!",
  "The key to your financial success is #Chiliz. Join #MillionarMap today!",
  "Start building your wealth with #Chiliz and #MillionarMap. Join now!",
  "The #Chiliz blockchain is waiting for you. Start making millions with #MillionarMap!",
  "Maximize your wealth potential with #Chiliz and #MillionarMap!",
  "Use the power of #Chiliz to unlock financial freedom. Join #MillionarMap today!",
  "Ready to make your fortune with #Chiliz and blockchain? Start with #MillionarMap!",
  "#Chiliz is the future of sports and finance. Join #MillionarMap to start your wealth journey!",
  "With #Chiliz and #MillionarMap, the path to millions is clear. Join now!",
  "Get rich with the power of #Chiliz. Start your millionaire journey on #MillionarMap today!",
  "Want to make millions with blockchain? #Chiliz is the way. Join #MillionarMap!",
  "Start building your fortune with #Chiliz and blockchain. Join #MillionarMap today!",
  "#Chiliz and blockchain are your keys to financial success. Get started on #MillionarMap!",
  "The #Chiliz blockchain opens doors to wealth. Join #MillionarMap today!",
  "Your future in wealth begins with #Chiliz and #MillionarMap. Join now!",
  "Get started with #Chiliz and blockchain to make millions! Join #MillionarMap!",
  "#Chiliz is shaping the future. Join #MillionarMap and secure your financial freedom!",
  "Don’t miss your chance to make millions with #Chiliz. Join #MillionarMap now!",
  "Join the #Chiliz revolution and start your wealth-building journey on #MillionarMap!",
  "Ready to start earning with #Chiliz? Join #MillionarMap today and build your fortune!",
  "#Chiliz is the future of finance. Start your journey to millionaire status with #MillionarMap!",
  "Building wealth is easy with #Chiliz and blockchain. Join #MillionarMap today!",
  "Let #Chiliz and blockchain technology lead you to financial freedom. Start with #MillionarMap!",
  "Your millionaire future starts with #Chiliz. Join #MillionarMap and get started now!",
  "Join #MillionarMap and let the power of #Chiliz help you achieve your dreams!",
  "Your path to millions is powered by #Chiliz and blockchain. Get started with #MillionarMap!",
  "Don’t wait! Start building your wealth with #Chiliz and #MillionarMap today!",
  "Ready to earn big with #Chiliz? Start your journey now on #MillionarMap!",
  "The time is now! Join #MillionarMap and start building your future with #Chiliz!",
  "Use #Chiliz and blockchain to unlock your financial success. Join #MillionarMap today!",
  "The million-dollar opportunity is here. Join #Chiliz and #MillionarMap today!",
  "Let #Chiliz and #MillionarMap be your guide to wealth. Join now and get started!",
  "Start earning today with #Chiliz and blockchain. Join #MillionarMap and make millions!",
  "Build your future with #Chiliz and #MillionarMap. The time is now!"
  ]


  export const TWEET_HEAD = [
    "Explore 🗺️ MillionarMap!",
    "Start now 🗺️ MillionarMap!",
    "Your map to wealth 🗺️ MillionarMap!",
    "Chart your path 🗺️ MillionarMap!",
    "Get rich 🗺️ MillionarMap!",
    "Unlock success 🗺️ MillionarMap!",
    "Your map 🗺️ MillionarMap!",
    "Wealth starts here 🗺️ MillionarMap!",
    "The path to riches 🗺️ MillionarMap!",
    "Start your journey 🗺️ MillionarMap!",
    "Follow the map 🗺️ MillionarMap!",
    "Wealth awaits 🗺️ MillionarMap!",
    "Success begins 🗺️ MillionarMap!",
    "Find your way 🗺️ MillionarMap!",
    "Get started 🗺️ MillionarMap!",
    "The road to riches 🗺️ MillionarMap!",
    "Your financial map 🗺️ MillionarMap!",
    "Map your success 🗺️ MillionarMap!",
    "Wealth is waiting 🗺️ MillionarMap!",
    "Unlock your future 🗺️ MillionarMap!",
    "The way to wealth 🗺️ MillionarMap!",
    "Start your wealth 🗺️ MillionarMap!",
    "Navigate success 🗺️ MillionarMap!",
    "Path to riches 🗺️ MillionarMap!",
    "Success map 🗺️ MillionarMap!",
    "Explore riches 🗺️ MillionarMap!",
    "Join now 🗺️ MillionarMap!",
    "Create your fortune 🗺️ MillionarMap!",
    "Your roadmap 🗺️ MillionarMap!",
    "The key to wealth 🗺️ MillionarMap!",
    "Map to millions 🗺️ MillionarMap!",
    "Start wealth now 🗺️ MillionarMap!",
    "Future unlocked 🗺️ MillionarMap!",
    "Chart your future 🗺️ MillionarMap!",
    "Discover wealth 🗺️ MillionarMap!",
    "Wealth map 🗺️ MillionarMap!",
    "Unlock the map 🗺️ MillionarMap!",
    "Find riches 🗺️ MillionarMap!",
    "Get the map 🗺️ MillionarMap!",
    "Start with MillionarMap 🗺️!",
    "Success path 🗺️ MillionarMap!",
    "Create wealth 🗺️ MillionarMap!",
    "Join MillionarMap 🗺️!",
    "Your future map 🗺️ MillionarMap!",
    "Financial journey 🗺️ MillionarMap!",
    "Find your fortune 🗺️ MillionarMap!",
    "Wealth path 🗺️ MillionarMap!",
    "Financial freedom 🗺️ MillionarMap!",
    "Map to success 🗺️ MillionarMap!",
    "The road to millions 🗺️ MillionarMap!",
    "Your path 🗺️ MillionarMap!",
    "Start building 🗺️ MillionarMap!",
    "The wealth journey 🗺️ MillionarMap!",
    "Get your map 🗺️ MillionarMap!",
    "Find success 🗺️ MillionarMap!",
    "Unlock your success 🗺️ MillionarMap!",
    "Chart your wealth 🗺️ MillionarMap!",
    "The path to fortune 🗺️ MillionarMap!",
    "Success unlocked 🗺️ MillionarMap!",
    "Start your journey now 🗺️ MillionarMap!",
    "Follow the millionaire path 🗺️ MillionarMap!",
    "Wealth is within reach 🗺️ MillionarMap!",
    "Your map to success 🗺️ MillionarMap!",
    "Journey to riches 🗺️ MillionarMap!",
    "The wealth map 🗺️ MillionarMap!",
    "Your financial future 🗺️ MillionarMap!"
  ]