export const TWITTER_USERS = [
   "ArghavanMeraji", "shaghaly_life", "GeLassenBTC", "GaryMa_Zhu", "ray_crypto", "louispellerin19", "Amin65611", "CodeSymphony", "vizitrexedi", "edisonlee55", "niiiixd", "alirezazaheri3", "SamiHeisenberg", "elina_mh", "Nafarzad", "m_mp07", "knock__back", "Doraaa1010", "manitehrani_", "saam_tehrani", "Rivendell09", "mozhtab", "HGhahari", "rezanasi61", "Masooooody", "Masooody", "mahdi_sharify", "iamtkey", "ashkan_arefi", "erfaanln", "Satoshitakamora", "Bahar19969", "Javadha616", "PacMoments", "realAminTakhti", "neeraj321996", "__N1995R__", "filmshouse24", "N0thing_00000", "0xgokhan", "903550072xjh", "ArgonStark", "maryambahadorii", "0x_migi", "NKhakzadi", "BMora2000", "4tt4r", "StarTreeTV", "MMitMM", "zkchun", "WeGoHam4Trey", "votewithid", "Ihatetw27596117", "MReza_Khan", "coconidodev", "Mori_11228", "SaeedehHamzeh", "MoradpourM", "MWTCrypto", "mor_xiaogan", "Josath1", "SirCloud7", "CollectorPi", "Behnaming", "h_mans", "s_naist", "Vigilante_313", "MohaghghiN", "mohsen_kho", "frs243", "nos486", "babamoradi77", "pasbanam", "lvlohamd7", "hamidt86", "haamiidt", "hamid_taghipour", "Amir34235710", "shojaeemo", "DocCLR", "shojaie_crypto", "Ineptant", "akp_devz", "smamn27", "RezaCrypto27", "a_mierr", "saeed_ghafouri", "Decentralverser", "Quiet_qx", "AmberBuchtela", "sjx198143", "sjx820544662", "ConnieAvalos11", "Merilyn50589774", "Sherice79841838", "haparootiii", "ivooos", "Wayfinderr11113", "jkcaeser", "SolitaryBG", "poozkhand", "DuongVanDong20", "phamtru57249070", "NgcThun64535287", "NamCungnh1", "Sebfox1", "HadiYousefy", "kimiadiscord", "Mohammadi1272", "amir_hobabi", "TemplarMiner", "madDeveloper0", "Susanne55183750", "kimiadiscord", "hshams", "LorenzzoLamazz", "yucheng62908873", "Okeke38", "chocoboplus", "hwayu000", "siksik2da", "Jacek_Czarnecki", "raha_eth", "snmousavi", "NilooNiloos", "orezsumni", "yue94578638", "Simon37449423", "iamzub_in", "jonstar67733001", "Cryptojimsilico", "kaminokemoriki", "misterdoice", "jbrukh", "mostafavi1990", "AbdulqadirZahra", "medrochatuk", "ch8992", "BHamshahri", "Hameda1Ms", "HessamInanloo", "HessamInanloo", "Pouriais", "cakoyo_", "aria55015635", "Alexand14160228", "Rminn", "starit1992", "theastrobloke", "Ido2022", "DanaFre78836657", "Bella777Holmes", "Coltron_eth", "AlanSafahi", "cory_eth", "berrios_eth", "AKcrypro", "Niharshah990", "philmohun", "nfteeez", "_Adontai", "cfa5321", "iamedwardtay", "sweartogod111", "wongmjane", "yamine_x", "Mohsen_AaK", "empera22r", "MrAsfariii", "0x2021", "Maytaylord", "DolhaC", "0xEnd3va", "jaarnie_gm", "muh_muh09", "SogeUsoppGod", "SamRadOfficial", "GregoryHenderl2", "treyshelton", "hexenq_eth", "nia_org", "CryptyLtd", "ba33ey", "juludith", "zkchun", "SobaLoggy", "zkchun", "Art23621", "0xWhale_AG", "Catheri96284495", "Ali24195204", "Hamed70441522", "aalezeta6", "behroozA44", "santiaaagoooo", "Ali04623460", "picnicnorris", "Brandon21955310", "hitchhike19", "DailyBT30", "imaneh_ganji", "nabi_sarvi", "Harsh4694529389", "M0hammad_hasani", "anzceel", "tia_t_a", "lll35446770", "alpergintr", "joshua19921225", "Kennethutah13", "jordiie09", "Omid_Rezaeii", "Sina_ReZz", "behi198000", "MajidMo16007549", "PostArchitekt", "Avi_DAO", "DSalmanzadeh", "yang199492", "amadeobrands", "xand3r_eth", "ddadybayo", "CalBlockchain", "RafaeWaqarQazi", "gsern1", "hamed_ghodrati", "0xA72b", "TabassomArgi", "shelby_steidl", "nullbitio", "0xRustamov", "danilolessa", "daryljedwards", "steve0xp", "AntonHu28914800", "SebastianKruz1", "VincentLanger6", "ChrisJa71128665", "ReimannJakob", "MarcusMatusek", "DevnerB", "GalberJakub", "FMajorik", "KlausNian", "HannahM20481229", "MaxManno3", "HansHerma2", "GombeManta", "GantenTole", "NabilNana13", "DNurmann", "FaraiNurfa", "AbayaHasan", "HandikRamin", "AfwanShila", "lauren_nila", "lea_warden", "SamuelMusso2", "GeraldRamad", "FishmanLesi", "LishamTheresa", "RohmManfred", "List8M", "LorrianRebecca", "ElmaLorri", "AgunusN", "HansoWanno", "LCarborough", "DoreneLou", "markus_rizky", "AaronMartins12", "AdriannaLovie", "BethLu11", "AbhiAllahabadia", "nassarhayat", "OCoisen", "SariMeyra", "GoldbergJorie", "JodyMalorie", "AbanisMola", "LilliManger", "SebastianSusov1", "NToylez", "KSabbel", "JensSafner", "papa4enko", "Fl0ridaDan", "Fl0ridaDan", "0xWinger", "oneeyedbabe", "luminoir", "OCDAnalysis", "nathgilson", "0xkaki", "vladimir_ili4", "ben19762", "DiyahSven", "TAnggeht", "josephgbls124", "ohivoo", "GaraaWichter", "FWulflinger", "AsynWang", "MaragarMikaela", "MarcellusMica", "JoettaMargarita", "MarieCr82066915", "MckinleyWyno", "KokserCaster65", "KokserCaster65", "PetyaBazilik", "Fl0ridaDan", "Fl0ridaDan", "kubvil551", "Valenti49347066", "avantgardefi", "bparlan", "DanHsiu", "herogadget", "e_nzil", "Alla_2056", "Reganjreese", "isaakmon_zapata", "Blanklin8", "AmishCaravan", "maryanaraw", "mikelberlin", "ShahabZangeneh", "derekmartin_", "tetonfinance", "CoreyBrincks", "space_jockey923", "lixiaokang777", "jacky_luxue", "Marceli00676449", "KiernanGeo", "AKaBUMrhZa8GigY", "joshaustindev", "berrios_eth", "DKshad0w", "phasfernandes", "kbw", "BensonByun", "BradLayton", "TestorEl", "shawnlgrubb", "MetaMedallist", "soldealer1", "quantumlyy", "JonSimmons4", "iamaia8", "hi_Reverie", "carrie39491313", "spicypaprika_", "rayjfab1", "daqhris", "_marekSan_", "ethermetab", "ethermetab", "ethermetab", "BrianHa79616376", "0xwolrd", "ClairvoyantLabs", "BrianHa79616376", "BrianHa79616376", "ethermetab", "BrianHa79616376", "0xAliB", "SaeedSajjadi1", "ethermetab", "haj_bubba", "coinair1", "jamesrao2014", "ashiiirg", "toshiaki_takase", "wildmouse_", "isiahhill", "etrnlflme", "The3D_", "yuan_brad", "AlexSlobodnik", "gladstonecallum", "stevegachau", "Sebastinez87", "BaggedTaco", "daisuke", "akashi031no", "jhdcrux", "0x_zhaotaobo", "seanwbren", "0xKillTheBuddha", "HuHongjin", "Yandie180", "HonestCTIntern", "Abbaskiko2", "originaltemk", "blockchainjames", "NinjaSufer", "zkchun", "shufann", "frogmonkee", "akamo888", "AdeptCamp", "chaserchapman", "haleyrsum", "awbreslin", "samuchiha_eth", "mciccarelli", "dp141192vav", "RambodYahyaei", "bekhorash", "psychotic369", "kia_joony", "selfex5", "Adan__01", "xmc0077", "ginbitcoin", "cyf1133", "dadsad84046452", "Shahria59469310", "nikhilbaranwal", "luckyhu19", "1IIfbGqL42Xbxs6", "joo3641", "pradeepbv", "shin_darin", "RachelL16778491", "SamLee15464611", "RahimiArmin", "Tonys0x1018", "reallym404", "voltzlabs", "Mhmd___988", "0xRann", "CollaborateKing", "Nimajafarpor", "rathermercurial", "stonemac65", "justyouni_h", "MajidJaden", "muyangren5", "AnyingXiang", "boolee99086929", "lbycuriosity", "AgveMaxi", "jecherio", "luoxi319", "xnxAleksandr", "chicagodao_io", "StanfordCrypto"
]

export const EMOJIS = [
    "😊", "🚀", "🔥", "💎", "💰", "⚡", "🌍", "🎉", "🌟", "💡", "✨", "💥", 
    "🌈", "💯", "👑", "🎯", "🚨", "🤑", "👀", "🥇", "💬", "🎵", "⚔️", "🍀", 
    "📈", "💪", "🏆", "💥", "🌠", "🌙", "🦄", "🥂", "🎁", "🔑", "🍾", "🔮", 
    "🥳", "🎬", "🔔", "👑", "🌸", "🔥", "🍀", "💃", "🏅", "🏖️", "🏄‍♂️", "🧠", 
    "💭", "🤩", "🎮", "🦸‍♀️", "🦸‍♂️", "🕹️", "🍕", "🍔", "🍩", "🌮", "🍿"
  ];

 export const TWEETS = [
    "Help me become a millionaire! Join #MillionarMap and get started today!",
    "Ready to change your life? Sign up with my referral on #MillionarMap!",
    "Want to be rich? #MillionarMap is your way to go. Join me now!",
    "Unlock your millionaire potential with #MillionarMap. Let’s do this!",
    "Join #MillionarMap and let’s make millions together!",
    "This is your chance to become a millionaire! Join #MillionarMap with my referral.",
    "Millionaire life starts here! Join #MillionarMap now!",
    "Make your dreams a reality with #MillionarMap. Let’s get rich!",
    "Want to change your future? #MillionarMap is your key to success!",
    "Let’s start your millionaire journey together on #MillionarMap!",
    "Don’t wait to be rich! Join #MillionarMap and start today!",
    "#MillionarMap is the opportunity you’ve been waiting for. Join now!",
    "Your millionaire future is just one click away. Sign up on #MillionarMap!",
    "It’s time to level up! Start your millionaire journey with #MillionarMap!",
    "Want to be a millionaire? Sign up for #MillionarMap with my referral now!",
    "Join #MillionarMap and take control of your financial future!",
    "Become a millionaire with #MillionarMap. Get started today!",
    "Your path to wealth starts here. Join #MillionarMap with my link!",
    "Ready to get rich? #MillionarMap is the key. Join me!",
    "Start your millionaire journey today with #MillionarMap. Let’s go!",
    "The road to riches is waiting for you on #MillionarMap. Sign up now!",
    "With #MillionarMap, your wealth-building journey begins today!",
    "Want financial freedom? Let’s get started on #MillionarMap!",
    "Don’t just dream about being a millionaire. Join #MillionarMap and make it happen!",
    "Sign up for #MillionarMap and take the first step towards becoming a millionaire!",
    "This is your chance to change your life. Join #MillionarMap today!",
    "Become a millionaire with #MillionarMap! Sign up now!",
    "Start your millionaire story on #MillionarMap with me today!",
    "Change your life with #MillionarMap. Sign up and get started!",
    "Don’t miss your chance to be a millionaire. Join #MillionarMap!",
    "The journey to wealth starts with #MillionarMap. Sign up today!",
    "#MillionarMap is your chance to make millions. Join now!",
    "Ready to be a millionaire? #MillionarMap is the way. Let’s get started!",
    "Your financial freedom starts now! Join #MillionarMap!",
    "Sign up for #MillionarMap and unlock the millionaire in you!",
    "Time to become a millionaire! Join #MillionarMap today!",
    "Wealth is waiting for you on #MillionarMap. Sign up now!",
    "Take the first step to riches with #MillionarMap!",
    "#MillionarMap is your key to financial success. Join today!",
    "Want to be rich? Let’s start with #MillionarMap!",
    "Millionaire dreams? #MillionarMap is the way to make them real!",
    "Join #MillionarMap now and start working towards your millionaire future!",
    "Ready to get rich? Start on #MillionarMap today!",
    "The million-dollar opportunity is here. Join #MillionarMap now!",
    "Start building your wealth with #MillionarMap today!",
    "Join me on #MillionarMap and let’s make millions together!",
    "Wealth is within reach with #MillionarMap. Sign up now!",
    "Your millionaire future starts here with #MillionarMap!",
    "Don’t miss out on becoming a millionaire. Join #MillionarMap today!",
    "#MillionarMap is your opportunity to change your life. Sign up now!",
    "The path to wealth starts with #MillionarMap. Join now and get started!",
    "Start your millionaire journey with me! #MillionarMap is the way!",
    "Unlock your potential and join #MillionarMap today. Let’s make millions!",
    "Ready to be rich? The journey begins with #MillionarMap. Join me now!",
    "Take control of your financial future with #MillionarMap. Join now!",
    "A million dollars could be yours. Start on #MillionarMap today!",
    "The secret to becoming a millionaire is right here. #MillionarMap!",
    "It’s time to stop dreaming and start doing. Join #MillionarMap now!",
    "Join me on #MillionarMap and let’s reach new heights together!",
    "Wealth is just a click away. Sign up for #MillionarMap today!",
    "Your millionaire future starts now. Join #MillionarMap and take action!",
    "Start building wealth today with #MillionarMap. Let’s do this!",
    "This is the chance you’ve been waiting for. Join #MillionarMap and become a millionaire!",
    "Let’s make your millionaire dreams a reality with #MillionarMap!",
    "Join #MillionarMap and start earning your way to the top!",
    "Your millionaire future is just one step away. Take it with #MillionarMap!",
    "Millionaire status is within reach. Start on #MillionarMap today!",
    "Unlock financial freedom today. Join #MillionarMap now!",
    "The million-dollar opportunity is here. Don’t miss out on #MillionarMap!",
    "Becoming a millionaire has never been easier. Join #MillionarMap!",
    "Let’s turn your dreams into reality. Join #MillionarMap now!",
    "Want financial success? Start with #MillionarMap today!",
    "Start your millionaire journey today with the power of #MillionarMap!",
    "Join #MillionarMap and start making money today!",
    "This is your chance to become a millionaire. Join #MillionarMap now!",
    "The road to riches begins now. Join #MillionarMap and take the first step!",
    "Create your millionaire future with #MillionarMap. Join now!",
    "Don’t let this opportunity slip away. Join #MillionarMap today!",
    "Start building your wealth with #MillionarMap. Let’s get rich!",
    "Millionaire dreams can come true. Join #MillionarMap now!",
    "Take charge of your financial destiny. Join #MillionarMap today!",
    "Your path to a million starts here. Sign up for #MillionarMap!",
    "The journey to a million dollars starts with #MillionarMap. Join today!",
    "Ready to change your life? Join #MillionarMap and get started now!",
    "Let’s make millions together. Join #MillionarMap today!",
    "The millionaire opportunity you’ve been waiting for is here. Join #MillionarMap!",
    "Take the first step towards wealth. Join #MillionarMap today!",
    "Start your millionaire journey now with #MillionarMap!",
    "Your millionaire future is closer than you think. Join #MillionarMap!",
    "Ready to invest in your future? Join #MillionarMap today and start earning!",
    "Join #MillionarMap and take control of your financial destiny!",
    "Millionaire success starts with one decision. Join #MillionarMap now!",
    "This is your moment. Join #MillionarMap and get started on your wealth journey!",
    "The chance to be a millionaire is here. Don’t miss it. Join #MillionarMap!",
    "Start building the life of your dreams. Join #MillionarMap today!",
    "Let’s make a million together. Join #MillionarMap now!",
    "Ready to unlock your wealth with blockchain technology? Join #MillionarMap today!",
    "The future of finance is blockchain. Start your millionaire journey with #MillionarMap!",
    "Blockchain is the key to financial freedom. Join #MillionarMap now!",
    "Join the blockchain revolution and become a millionaire with #MillionarMap!",
    "Ready to earn with blockchain? Start today on #MillionarMap!",
    "Blockchain can make you a millionaire. Let’s start with #MillionarMap!",
    "Your million-dollar opportunity starts with blockchain on #MillionarMap!",
    "Blockchain + #MillionarMap = Your path to wealth! Join now!",
    "Want to invest in the future? Blockchain is the answer. Start with #MillionarMap!",
    "Change your financial future with blockchain. Join #MillionarMap today!",
    "Blockchain technology is the future. Join #MillionarMap and get rich!",
    "The best way to build wealth? Blockchain. Join #MillionarMap today!",
    "Blockchain is the future of money. Get ahead with #MillionarMap!",
    "Become a blockchain millionaire with #MillionarMap. Join today!",
    "Blockchain is the key to unlocking millions. Start with #MillionarMap!",
    "Ready to build wealth through blockchain? Start on #MillionarMap now!",
    "Blockchain is changing everything. Join #MillionarMap and be part of it!",
    "Unlock your financial success with blockchain on #MillionarMap!",
    "The power of blockchain is yours to harness on #MillionarMap. Join now!",
    "Wealth is built on blockchain technology. Join #MillionarMap to get started!",
    "Blockchain + #MillionarMap = Your ticket to financial success!",
    "Join the blockchain boom and start building your fortune with #MillionarMap!",
    "Start making money with blockchain. Join #MillionarMap today!",
    "Blockchain makes millionaire dreams come true. Start with #MillionarMap!",
    "Ready to use blockchain to get rich? Join #MillionarMap today!",
    "The blockchain era is here. Join #MillionarMap and build your fortune!",
    "Blockchain is the foundation for future wealth. Start with #MillionarMap now!",
    "Your path to millions is powered by blockchain. Join #MillionarMap!",
    "Blockchain technology can make you rich. Join #MillionarMap today!",
    "Take control of your financial destiny with blockchain. Join #MillionarMap!",
    "The future is blockchain. Get started on your millionaire journey with #MillionarMap!",
    "Blockchain is changing how we make money. Join #MillionarMap today!",
    "Start earning through blockchain. Join #MillionarMap now!",
    "Blockchain is revolutionizing finance. Join #MillionarMap and get rich!",
    "Your blockchain-powered future starts now. Join #MillionarMap!",
    "Blockchain and #MillionarMap are the keys to your financial success!",
    "The wealth-building power of blockchain is here. Join #MillionarMap today!",
    "Don’t miss out on blockchain wealth. Join #MillionarMap now!",
    "Ready to make money with blockchain? Start on #MillionarMap today!",
    "Blockchain is your gateway to a millionaire future. Join #MillionarMap!",
    "Get rich with blockchain and #MillionarMap. Join today!",
    "Blockchain wealth starts here. Join #MillionarMap and get started!",
    "The blockchain future is yours. Join #MillionarMap and make millions!",
    "Blockchain is the new gold. Start mining your wealth with #MillionarMap!",
    "Don’t just watch blockchain’s rise, be a part of it. Join #MillionarMap!",
    "Your path to blockchain riches starts today. Join #MillionarMap!",
    "Blockchain is the future of wealth. Get started now with #MillionarMap!",
    "Start your blockchain journey and become a millionaire with #MillionarMap!",
    "Join the #Chiliz movement and start your millionaire journey today with #MillionarMap!",
  "Ready to get rich with blockchain and #Chiliz? Join #MillionarMap now!",
  "#Chiliz is the future of sports and blockchain. Get in on the action with #MillionarMap!",
  "Unlock your wealth with #Chiliz and #MillionarMap. Join now!",
  "Become a millionaire with #Chiliz and blockchain technology. Start with #MillionarMap!",
  "Take control of your financial future with #Chiliz and #MillionarMap!",
  "The combination of #Chiliz and blockchain is your ticket to wealth. Join #MillionarMap!",
  "Join #MillionarMap today and use the power of #Chiliz to make millions!",
  "Ready to change your life with #Chiliz and blockchain? Get started on #MillionarMap!",
  "The #Chiliz blockchain is your opportunity to get rich. Join #MillionarMap now!",
  "Start your journey to wealth with #Chiliz and blockchain. Join #MillionarMap!",
  "#Chiliz and #MillionarMap are the perfect pair to make your dreams come true. Join now!",
  "Use the power of #Chiliz and #MillionarMap to unlock financial success!",
  "The future is #Chiliz. Join #MillionarMap and build your wealth today!",
  "Join #MillionarMap and let #Chiliz help you create your millionaire future!",
  "Don’t miss out on the #Chiliz revolution. Start your millionaire journey with #MillionarMap!",
  "Ready to earn with #Chiliz and blockchain? Join #MillionarMap and get started today!",
  "Your millionaire future is powered by #Chiliz and blockchain. Join #MillionarMap now!",
  "The key to your financial success is #Chiliz. Join #MillionarMap today!",
  "Start building your wealth with #Chiliz and #MillionarMap. Join now!",
  "The #Chiliz blockchain is waiting for you. Start making millions with #MillionarMap!",
  "Maximize your wealth potential with #Chiliz and #MillionarMap!",
  "Use the power of #Chiliz to unlock financial freedom. Join #MillionarMap today!",
  "Ready to make your fortune with #Chiliz and blockchain? Start with #MillionarMap!",
  "#Chiliz is the future of sports and finance. Join #MillionarMap to start your wealth journey!",
  "With #Chiliz and #MillionarMap, the path to millions is clear. Join now!",
  "Get rich with the power of #Chiliz. Start your millionaire journey on #MillionarMap today!",
  "Want to make millions with blockchain? #Chiliz is the way. Join #MillionarMap!",
  "Start building your fortune with #Chiliz and blockchain. Join #MillionarMap today!",
  "#Chiliz and blockchain are your keys to financial success. Get started on #MillionarMap!",
  "The #Chiliz blockchain opens doors to wealth. Join #MillionarMap today!",
  "Your future in wealth begins with #Chiliz and #MillionarMap. Join now!",
  "Get started with #Chiliz and blockchain to make millions! Join #MillionarMap!",
  "#Chiliz is shaping the future. Join #MillionarMap and secure your financial freedom!",
  "Don’t miss your chance to make millions with #Chiliz. Join #MillionarMap now!",
  "Join the #Chiliz revolution and start your wealth-building journey on #MillionarMap!",
  "Ready to start earning with #Chiliz? Join #MillionarMap today and build your fortune!",
  "#Chiliz is the future of finance. Start your journey to millionaire status with #MillionarMap!",
  "Building wealth is easy with #Chiliz and blockchain. Join #MillionarMap today!",
  "Let #Chiliz and blockchain technology lead you to financial freedom. Start with #MillionarMap!",
  "Your millionaire future starts with #Chiliz. Join #MillionarMap and get started now!",
  "Join #MillionarMap and let the power of #Chiliz help you achieve your dreams!",
  "Your path to millions is powered by #Chiliz and blockchain. Get started with #MillionarMap!",
  "Don’t wait! Start building your wealth with #Chiliz and #MillionarMap today!",
  "Ready to earn big with #Chiliz? Start your journey now on #MillionarMap!",
  "The time is now! Join #MillionarMap and start building your future with #Chiliz!",
  "Use #Chiliz and blockchain to unlock your financial success. Join #MillionarMap today!",
  "The million-dollar opportunity is here. Join #Chiliz and #MillionarMap today!",
  "Let #Chiliz and #MillionarMap be your guide to wealth. Join now and get started!",
  "Start earning today with #Chiliz and blockchain. Join #MillionarMap and make millions!",
  "Build your future with #Chiliz and #MillionarMap. The time is now!"
  ]


  export const TWEET_HEAD = [
    "Explore 🗺️ MillionarMap!",
    "Start now 🗺️ MillionarMap!",
    "Your map to wealth 🗺️ MillionarMap!",
    "Chart your path 🗺️ MillionarMap!",
    "Get rich 🗺️ MillionarMap!",
    "Unlock success 🗺️ MillionarMap!",
    "Your map 🗺️ MillionarMap!",
    "Wealth starts here 🗺️ MillionarMap!",
    "The path to riches 🗺️ MillionarMap!",
    "Start your journey 🗺️ MillionarMap!",
    "Follow the map 🗺️ MillionarMap!",
    "Wealth awaits 🗺️ MillionarMap!",
    "Success begins 🗺️ MillionarMap!",
    "Find your way 🗺️ MillionarMap!",
    "Get started 🗺️ MillionarMap!",
    "The road to riches 🗺️ MillionarMap!",
    "Your financial map 🗺️ MillionarMap!",
    "Map your success 🗺️ MillionarMap!",
    "Wealth is waiting 🗺️ MillionarMap!",
    "Unlock your future 🗺️ MillionarMap!",
    "The way to wealth 🗺️ MillionarMap!",
    "Start your wealth 🗺️ MillionarMap!",
    "Navigate success 🗺️ MillionarMap!",
    "Path to riches 🗺️ MillionarMap!",
    "Success map 🗺️ MillionarMap!",
    "Explore riches 🗺️ MillionarMap!",
    "Join now 🗺️ MillionarMap!",
    "Create your fortune 🗺️ MillionarMap!",
    "Your roadmap 🗺️ MillionarMap!",
    "The key to wealth 🗺️ MillionarMap!",
    "Map to millions 🗺️ MillionarMap!",
    "Start wealth now 🗺️ MillionarMap!",
    "Future unlocked 🗺️ MillionarMap!",
    "Chart your future 🗺️ MillionarMap!",
    "Discover wealth 🗺️ MillionarMap!",
    "Wealth map 🗺️ MillionarMap!",
    "Unlock the map 🗺️ MillionarMap!",
    "Find riches 🗺️ MillionarMap!",
    "Get the map 🗺️ MillionarMap!",
    "Start with MillionarMap 🗺️!",
    "Success path 🗺️ MillionarMap!",
    "Create wealth 🗺️ MillionarMap!",
    "Join MillionarMap 🗺️!",
    "Your future map 🗺️ MillionarMap!",
    "Financial journey 🗺️ MillionarMap!",
    "Find your fortune 🗺️ MillionarMap!",
    "Wealth path 🗺️ MillionarMap!",
    "Financial freedom 🗺️ MillionarMap!",
    "Map to success 🗺️ MillionarMap!",
    "The road to millions 🗺️ MillionarMap!",
    "Your path 🗺️ MillionarMap!",
    "Start building 🗺️ MillionarMap!",
    "The wealth journey 🗺️ MillionarMap!",
    "Get your map 🗺️ MillionarMap!",
    "Find success 🗺️ MillionarMap!",
    "Unlock your success 🗺️ MillionarMap!",
    "Chart your wealth 🗺️ MillionarMap!",
    "The path to fortune 🗺️ MillionarMap!",
    "Success unlocked 🗺️ MillionarMap!",
    "Start your journey now 🗺️ MillionarMap!",
    "Follow the millionaire path 🗺️ MillionarMap!",
    "Wealth is within reach 🗺️ MillionarMap!",
    "Your map to success 🗺️ MillionarMap!",
    "Journey to riches 🗺️ MillionarMap!",
    "The wealth map 🗺️ MillionarMap!",
    "Your financial future 🗺️ MillionarMap!"
  ]